// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.0-rc7

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type PianoHTTPServer interface {
	CreatePiano(context.Context, *CreatePianoRequest) (*CreatePianoReply, error)
}

func RegisterPianoHTTPServer(s *http.Server, srv PianoHTTPServer) {
	r := s.Route("/")
	r.GET("/v1.service.create", _Piano_CreatePiano0_HTTP_Handler(srv))
}

func _Piano_CreatePiano0_HTTP_Handler(srv PianoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePianoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.piano.v1.Piano/CreatePiano")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePiano(ctx, req.(*CreatePianoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePianoReply)
		return ctx.Result(200, reply)
	}
}

type PianoHTTPClient interface {
	CreatePiano(ctx context.Context, req *CreatePianoRequest, opts ...http.CallOption) (rsp *CreatePianoReply, err error)
}

type PianoHTTPClientImpl struct {
	cc *http.Client
}

func NewPianoHTTPClient(client *http.Client) PianoHTTPClient {
	return &PianoHTTPClientImpl{client}
}

func (c *PianoHTTPClientImpl) CreatePiano(ctx context.Context, in *CreatePianoRequest, opts ...http.CallOption) (*CreatePianoReply, error) {
	var out CreatePianoReply
	pattern := "/v1.service.create"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.piano.v1.Piano/CreatePiano"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
