// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.17.1
// source: api/piano/v1/piano.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePianoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime int64  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *CreatePianoRequest) Reset() {
	*x = CreatePianoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePianoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePianoRequest) ProtoMessage() {}

func (x *CreatePianoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePianoRequest.ProtoReflect.Descriptor instead.
func (*CreatePianoRequest) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePianoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatePianoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePianoRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreatePianoRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type CreatePianoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreatePianoReply) Reset() {
	*x = CreatePianoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePianoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePianoReply) ProtoMessage() {}

func (x *CreatePianoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePianoReply.ProtoReflect.Descriptor instead.
func (*CreatePianoReply) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePianoReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreatePianoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdatePianoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePianoRequest) Reset() {
	*x = UpdatePianoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePianoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePianoRequest) ProtoMessage() {}

func (x *UpdatePianoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePianoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePianoRequest) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{2}
}

type UpdatePianoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePianoReply) Reset() {
	*x = UpdatePianoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePianoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePianoReply) ProtoMessage() {}

func (x *UpdatePianoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePianoReply.ProtoReflect.Descriptor instead.
func (*UpdatePianoReply) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{3}
}

type DeletePianoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePianoRequest) Reset() {
	*x = DeletePianoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePianoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePianoRequest) ProtoMessage() {}

func (x *DeletePianoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePianoRequest.ProtoReflect.Descriptor instead.
func (*DeletePianoRequest) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{4}
}

type DeletePianoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePianoReply) Reset() {
	*x = DeletePianoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePianoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePianoReply) ProtoMessage() {}

func (x *DeletePianoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePianoReply.ProtoReflect.Descriptor instead.
func (*DeletePianoReply) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{5}
}

type GetPianoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPianoRequest) Reset() {
	*x = GetPianoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPianoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPianoRequest) ProtoMessage() {}

func (x *GetPianoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPianoRequest.ProtoReflect.Descriptor instead.
func (*GetPianoRequest) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{6}
}

type GetPianoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPianoReply) Reset() {
	*x = GetPianoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPianoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPianoReply) ProtoMessage() {}

func (x *GetPianoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPianoReply.ProtoReflect.Descriptor instead.
func (*GetPianoReply) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{7}
}

type ListPianoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPianoRequest) Reset() {
	*x = ListPianoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPianoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPianoRequest) ProtoMessage() {}

func (x *ListPianoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPianoRequest.ProtoReflect.Descriptor instead.
func (*ListPianoRequest) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{8}
}

type ListPianoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPianoReply) Reset() {
	*x = ListPianoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_piano_v1_piano_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPianoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPianoReply) ProtoMessage() {}

func (x *ListPianoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_piano_v1_piano_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPianoReply.ProtoReflect.Descriptor instead.
func (*ListPianoReply) Descriptor() ([]byte, []int) {
	return file_api_piano_v1_piano_proto_rawDescGZIP(), []int{9}
}

var File_api_piano_v1_piano_proto protoreflect.FileDescriptor

var file_api_piano_v1_piano_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69,
	0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69,
	0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50,
	0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0xa9, 0x03, 0x0a, 0x05, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x12, 0x6b, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x4f, 0x0a, 0x0b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69,
	0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x69,
	0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x69, 0x61,
	0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f,
	0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2c,
	0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x50, 0x01,
	0x5a, 0x1a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x69, 0x61, 0x6e, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_piano_v1_piano_proto_rawDescOnce sync.Once
	file_api_piano_v1_piano_proto_rawDescData = file_api_piano_v1_piano_proto_rawDesc
)

func file_api_piano_v1_piano_proto_rawDescGZIP() []byte {
	file_api_piano_v1_piano_proto_rawDescOnce.Do(func() {
		file_api_piano_v1_piano_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_piano_v1_piano_proto_rawDescData)
	})
	return file_api_piano_v1_piano_proto_rawDescData
}

var file_api_piano_v1_piano_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_piano_v1_piano_proto_goTypes = []interface{}{
	(*CreatePianoRequest)(nil), // 0: api.piano.v1.CreatePianoRequest
	(*CreatePianoReply)(nil),   // 1: api.piano.v1.CreatePianoReply
	(*UpdatePianoRequest)(nil), // 2: api.piano.v1.UpdatePianoRequest
	(*UpdatePianoReply)(nil),   // 3: api.piano.v1.UpdatePianoReply
	(*DeletePianoRequest)(nil), // 4: api.piano.v1.DeletePianoRequest
	(*DeletePianoReply)(nil),   // 5: api.piano.v1.DeletePianoReply
	(*GetPianoRequest)(nil),    // 6: api.piano.v1.GetPianoRequest
	(*GetPianoReply)(nil),      // 7: api.piano.v1.GetPianoReply
	(*ListPianoRequest)(nil),   // 8: api.piano.v1.ListPianoRequest
	(*ListPianoReply)(nil),     // 9: api.piano.v1.ListPianoReply
}
var file_api_piano_v1_piano_proto_depIdxs = []int32{
	0, // 0: api.piano.v1.Piano.CreatePiano:input_type -> api.piano.v1.CreatePianoRequest
	2, // 1: api.piano.v1.Piano.UpdatePiano:input_type -> api.piano.v1.UpdatePianoRequest
	4, // 2: api.piano.v1.Piano.DeletePiano:input_type -> api.piano.v1.DeletePianoRequest
	6, // 3: api.piano.v1.Piano.GetPiano:input_type -> api.piano.v1.GetPianoRequest
	8, // 4: api.piano.v1.Piano.ListPiano:input_type -> api.piano.v1.ListPianoRequest
	1, // 5: api.piano.v1.Piano.CreatePiano:output_type -> api.piano.v1.CreatePianoReply
	3, // 6: api.piano.v1.Piano.UpdatePiano:output_type -> api.piano.v1.UpdatePianoReply
	5, // 7: api.piano.v1.Piano.DeletePiano:output_type -> api.piano.v1.DeletePianoReply
	7, // 8: api.piano.v1.Piano.GetPiano:output_type -> api.piano.v1.GetPianoReply
	9, // 9: api.piano.v1.Piano.ListPiano:output_type -> api.piano.v1.ListPianoReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_piano_v1_piano_proto_init() }
func file_api_piano_v1_piano_proto_init() {
	if File_api_piano_v1_piano_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_piano_v1_piano_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePianoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePianoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePianoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePianoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePianoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePianoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPianoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPianoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPianoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_piano_v1_piano_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPianoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_piano_v1_piano_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_piano_v1_piano_proto_goTypes,
		DependencyIndexes: file_api_piano_v1_piano_proto_depIdxs,
		MessageInfos:      file_api_piano_v1_piano_proto_msgTypes,
	}.Build()
	File_api_piano_v1_piano_proto = out.File
	file_api_piano_v1_piano_proto_rawDesc = nil
	file_api_piano_v1_piano_proto_goTypes = nil
	file_api_piano_v1_piano_proto_depIdxs = nil
}
